version: "3"
services:
    db1:
        build: ./db1
        environment:
            SA_PASSWORD: "MssqlPass123"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "2500:1433"
        container_name: db1
        hostname: db1
    db2:
        build: ./db2
        environment:
            SA_PASSWORD: "MssqlPass123"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "2600:1433"
        container_name: db2
        hostname: db2

