apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mssql
    pod-template-hash: 7b6565d684
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: mssql-deployment-7b6565d684
      uid: 676d104c-c041-11e9-b5fa-c6f80bad26d8
spec:
  containers:
    - env:
        - name: MSSQL_PID
          value: Developer
        - name: ACCEPT_EULA
          value: 'Y'
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SA_PASSWORD
              name: mssql-secret
      image: 'mcr.microsoft.com/mssql/rhel/server:2019-latest'
      imagePullPolicy: IfNotPresent
      name: mssql
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssqldb
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-bw2rt
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-90949249-0
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 10
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: mssqldb
      persistentVolumeClaim:
        claimName: mssql-data
    - name: default-token-bw2rt
      secret:
        defaultMode: 420
        secretName: default-token-bw2rt
